spring:
  application:
    name: Car4U
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "http://localhost:3000/auth/google/callback"
            authorization-grant-type: authorization_code
            client-name: Google
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - public_profile
              - email
            redirect-uri: "http://localhost:3000/auth/facebook/callback"
            authorization-grant-type: authorization_code
            client-name: Facebook
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          facebook:
            authorization-uri: https://www.facebook.com/v22.0/dialog/oauth
            token-uri: https://graph.facebook.com/v22.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture,type(large)

server:
  port: 8080
#  servlet:
#    context-path: /api/v1

app:
  mongodb:
    uri: ${MONGO_URL}
  jwt:
    signer-key: ${JWT_SIGNER_KEY}
  payment:
    vnPay:
      url: ${PAY_URL}
      tmnCode: ${TMN_CODE}
      secretKey: ${SECRET_KEY}
      returnUrl: ${RETURN_URL}
      version: ${VERSION}
      command: ${COMMAND}
      orderType: ${ORDER_TYPE}
  aws:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    s3-bucket-name: ${AWS_S3_BUCKET_NAME}
    cloudfront-url: ${AWS_CLOUDFRONT_URL}
  gemini:
    api-key: ${GEMINI_AI_KEY}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html